### PR TITLE
Make plotters more prominent, move out from under examples dir

### PR DESCRIPTION
**Pull request by klaukh**
Would like to see the plotters moved out from under the examples directory to make this capability more prominent, hopefully encouraging further development from the community.  I moved the folder out to be a peer with the plugins dir, and moved the candlestick.js file to the plotters since it is indeed a plotter rather than a plugin.  Changed the custom-plotters .html and .Rmd to match.

### CODE REVIEW

**Comment by jjallaire** [comment]
I think for dyCandlestick this is a fine change (and hopefully will as you said encourage more plotters). The other code though are actually for examples so to me belong in the examples folder (so as to make it clear they aren't first-order features of the package).

**Comment by klaukh** [comment]
Understood.  Incidentally, I'm one of those currently encouraged to do more plotters.  I'm working on some more updates to make them applicable on a per-series basis and (hopefully) group basis.  As they stand, the current example plotters act upon the entire data in the dygraph, but the code base can already support most per-series plotters.  I'll submit a pull request for those once ready for review, and maybe ask you to reconsider elevation of those to the plotters folder since the ability to mix-and-match would be an enticing extension of capability - in my opinion on-par with plugins. I've seen the issue brought up in other forums.

The group-based plotters (like multicolumn or candlestick on a specified subset of the data rather than the whole data) may require a few changes to the code base.  I'm still brainstorming how to accomplish that smoothly

**Comment by jjallaire** [comment]
Okay, that all sounds great!

**Comment by klaukh** [comment]
Latest commits in my repo now open the ability to do plotters on a per-series basis.  I mod'd plotter.R to have some examples.  I can either stick with this pull req or close it and open another with the full capability - whichever is more convenient.  I'm still working on stacked series groups... a little more complicated... maybe someone else can beat me to it.  Happy to discuss underlying logic of the dyGroup (series group) here or through another forum if more clarity needed.

As per above comments, I personally believe the per-series and per-group plotter capabilities now make plotters equal with plugins, so kindly requesting reconsideration for elevating the plotters folder out from under the examples folder.

**Comment by jjallaire** [comment]
I have no problem with plotters being moved out of examples once they are not actually used as examples (the two in there now are used only in the page which describes how to create custom plotters). If we want to promote those to full scale features (and export and document the `dyBarChart` and `dyMultiColumn` functions) then they can move out of examples.

Along the same lines it looks like the contents of `inst/plotters/plotters.R` really wants to be moved into `R/plotters.R` and those functions exported and documented. Do you agree?

**Comment by klaukh** [comment]
Agree.  Happy to cut that and push a new commit from my repo so everything is in one place for you.  Would need through the coming weekend to process...

**Comment by jjallaire** [comment]
Okay, sounds good!

**Comment by klaukh** [comment]
Pushed a hack on the documentation.  Quick note: the combined Rd also has the dyCandlestick merged, so my latest commit has the dyCandlestick.Rd deleted.

**Comment by klaukh** [comment]
@jjallaire, New set of plotters ready, with documentation.  I added the ability to do stacked groups and other stacked charts via plotters, allowing users to mix-and-match different viz options on the same chart. Hopefully that might provide some inspiration to others for more plotters!   See charts below for examples of the new options:

image

image

image

image

+1 to @jeffreyhanson for the dySliderInput plugin... would enjoy having that available from a CRAN dygraphs installation as well

**Comment by jjallaire** [comment]
Fantastic!!! I'll merge this now.

It would also be good to add these new plotters to the website documentation (source code for the R Markdown website is here: https://github.com/rstudio/dygraphs/tree/master/docs).

**Pull request merged**
