### PR TITLE
Candlestick plotter

### PR DESCRIPTION
**Pull request by pshevtsov**
This PR introduces the `dyCandlestick` function to render Candlestick/OHLC chart with dygraphs:

```
library(xts)
data(sample_matrix)
library(dygraphs)
dygraph(sample <- matrix) %>%
  dyCandlestick()
```

and the output is the following:
candlestick

_This PR implements some features discussed in #3_ 
CC: @danielkrizian

### CODE REVIEW

**Comment by renkun-ken** [comment]
Looks nice!

**Comment by jjallaire** [comment]
Does this impose any requirements on the input data (e.g. number of series). If so perhaps the function should validate that and throw an error if the data isn't as required.

**Comment by pshevtsov** [comment]
@jjallaire it checks for the number of series on the JavaScript side, i.e. if the number of series is lesser than four it switches back to line plotter, otherwise if the amount of series is greater than four it plots the first four series with candlestick plotter and the rest with line plotter.
2016-10-29-064734_666x344_scrot

**Comment by jjallaire** [comment]
@pshevtsov This is looking great. I've moved the documentation into the `docs/` folder. Could you add a page about the candlestick plugin? You just need to create an Rmd (e.g. "gallery-candlestick.Rmd") in the fashion of the other ones then add a link to it from the sidebar (https://github.com/rstudio/dygraphs/blob/master/docs/include/before_body.html)

**Comment by pshevtsov** [comment]
@jjallaire Sure thing! BTW, how should I generate html file from that Rmd one?

**Comment by jjallaire** [comment]
Just call rmarkdown::render_site within the docs directory

**Comment by pshevtsov** [comment]
@jjallaire Ready. I decided not to commit generated `*.html` files, since the output seems to be system dependent and the diff with the upstream was huge.

**Pull request merged**
