### PR TITLE
update to dygraphs 1.1

### PR DESCRIPTION
**Pull request by jjallaire**
I've combined all of the previous work (including the original PR from @pshevtsov as well as cherry-picked changes from https://github.com/rstudio/dygraphs/pull/88 by @chrisirhc. There are two outstanding issues:

1) When dygraphs 1.1 formats years on the x-axis it attempts to use only decade tick marks. This results in some odd looking axes like this:

screen shot 2015-10-13 at 9 26 13 am

The code that generated this is here: http://rstudio.github.io/dygraphs/gallery-axis-options.html

This represents a change in behavior that will likely annoying to users that are plotting intervals over < ~30 years. Perhaps there is something we can tweak in dygraphs to change this behavior (I haven't yet been able to find it).

2) The `useDataTimezone` option which was implemented using moment.js no longer works  (it throws a JS exception). The issues appears to be that the `Dygraph.SHORT_SPACINGS` object previously used by our custom axis formatter no longer exists:

screen shot 2015-10-13 at 9 30 02 am

@bthieurmel Could you take a look at re-writing this to be compatible with dygraphs 1.1?

### CODE REVIEW

**Comment by bthieurmel** [comment]
Hi,

````dygraph```` change a lot of internal function / method, so it's "logical" that ````useDataTimezone```` no longers works.

I 've already do the migration few month ago to update ````useDataTimezone```` for 1.1

Can try to take some time in the next days to try to merge this work...

**Comment by jjallaire** [comment]
Okay, great! If you could open those changes up as a PR against the feature/dygraphs-1.1 branch (https://github.com/rstudio/dygraphs/tree/feature/dygraphs-1.1) that would be great.

**Comment by chrisirhc** [comment]
@jjallaire , it looks like you decided to use the axisLabelWidth of 60? Did you see the changes to retain the 2-digit years for the x axis formatting in #88 ?

**Comment by bthieurmel** [comment]
fix ````useDataTimezone``` in useDataTimezone for dygraph 1.1 #90

**Comment by jjallaire** [comment]
I did see those changes but decided not to take them. Upon reflecting further I think it's better to preserve the underlying dygraphs behavior even though it makes some axis display less than ideal (my hope is that these issues end up being fixed in the underlying library).

**Comment by chrisirhc** [comment]
The dygraphs library doesn't seem to think that it's a bug. I doubt it'll be fixed. Did you report the issue? I've linked an issue in the discussion, where the suggestion was to change the label width.

**Comment by jjallaire** [comment]
Agreed. I think we'll just have to live with it and folks can change the
label width if need be.

**Pull request merged**
